;CMD File for Misty , don't copy anything
;===========================================================================
;===========================================================================
;AI activation commands
;===========================================================================
[Command]
name = "CPU1"
command = a,a,a,a
time = 1

[Command]
name = "CPU2"
command = b,b,b,b
time = 1

[Command]
name = "CPU3"
command = c,c,c,c
time = 1

[Command]
name = "CPU4"
command = x,x,x,x
time = 1

[Command]
name = "CPU5"
command = y,y,y,y
time = 1

[Command]
name = "CPU6"
command = z,z,z,z
time = 1

[Command]
name = "CPU7"
command = a,b,c,x,y,z
time = 1

[Command]
name = "CPU8"
command = b,c,x,y,z,a
time = 1

[Command]
name = "CPU9"
command = c,x,y,z,a,b
time = 1

[Command]
name = "CPU10"
command = x,y,z,a,b,c
time = 1

[Command]
name = "CPU11"
command = y,z,a,b,c,x
time = 1

[Command]
name = "CPU12"
command = z,a,b,c,x,y
time = 1

[Command]
name = "CPU13"
command = z,y,x,c,b,a
time = 1

[Command]
name = "CPU14"
command = y,x,c,b,a,z
time = 1

[Command]
name = "CPU15"
command = x,c,b,a,z,y
time = 1

[Command]
name = "CPU16"
command = c,b,a,z,y,x
time = 1

[Command]
name = "CPU17"
command = b,a,z,y,x,c
time = 1

[Command]
name = "CPU18"
command = a,z,y,x,c,b
time = 1

[Command]
name = "CPU19"
command = a,b,a,b
time = 1

[Command]
name = "CPU20"
command = a,c,a,c
time = 1

[Command]
name = "CPU21"
command = a,x,a,x
time = 1

[Command]
name = "CPU22"
command = a,y,a,y
time = 1

[Command]
name = "CPU23"
command = a,z,a,z
time = 1

[Command]
name = "CPU24"
command = b,a,b,a
time = 1

[Command]
name = "CPU25"
command = b,c,b,c
time = 1

[Command]
name = "CPU26"
command = b,x,b,x
time = 1

[Command]
name = "CPU27"
command = b,y,b,y
time = 1

[Command]
name = "CPU28"
command = b,z,b,z
time = 1

[Command]
name = "CPU29"
command = c,a,c,a
time = 1

[Command]
name = "CPU30"
command = c,b,c,b
time = 1

[Command]
name = "CPU31"
command = c,x,c,x
time = 1

[Command]
name = "CPU32"
command = c,y,c,y
time = 1

[Command]
name = "CPU33"
command = c,z,c,z
time = 1

[Command]
name = "CPU34"
command = x,a,x,a
time = 1

[Command]
name = "CPU35"
command = x,b,x,b
time = 1

[Command]
name = "CPU36"
command = x,c,x,c
time = 1

[Command]
name = "CPU37"
command = x,y,x,y
time = 1

[Command]
name = "CPU38"
command = x,z,x,z
time = 1

[Command]
name = "CPU39"
command = y,a,y,a
time = 1

[Command]
name = "CPU40"
command = y,b,y,b
time = 1

[Command]
name = "CPU41"
command = y,c,y,c
time = 1

[Command]
name = "CPU42"
command = y,x,y,x
time = 1

[Command]
name = "CPU43"
command = y,z,y,z
time = 1

[Command]
name = "CPU44"
command = z,a,z,a
time = 1

[Command]
name = "CPU45"
command = z,b,z,b
time = 1

[Command]
name = "CPU46"
command = z,c,z,c
time = 1

[Command]
name = "CPU47"
command = z,x,z,x
time = 1

[Command]
name = "CPU48"
command = z,y,z,y
time = 1

; Hyper Motions
;===========================================================================
;Marvel Triper
[Command]
name = "mt"
command = ~B,D,F,x
time = 30

[Command]
name = "mt"
command = ~B,D,F,y
time = 30

[Command]
name = "mt"
command = ~B,D,F,z
time = 30

;Vertical Marvel Triper
[Command]
name = "vmt1"
command = ~F,D,B,x
time = 30

[Command]
name = "vmt2"
command = ~F,D,B,y
time = 30

[Command]
name = "vmt3"
command = ~F,D,B,z
time = 30

;Big Marvel Triper
[Command]
name = "mt2"
command = ~D,B,F,D,B,x
time = 30

[Command]
name = "mt2"
command = ~D,B,F,D,B,y
time = 30

[Command]
name = "mt2"
command = ~D,B,F,D,B,z
time = 30
;===========================================================================
; Super Motions
;===========================================================================
;slide nudge
[Command]
name = "nudge1"
command = D,B,x
time = 30

[Command]
name = "nudge2"
command = D,B,y
time = 30

[Command]
name = "nudge3"
command = D,B,z
time = 30

;throw
[Command]
name = "throw"
command = x

[Command]
name = "throw"
command = y

[Command]
name = "throw"
command = z

;multi kick
[Command]
name = "multikick"
command = F,D,F,a
time = 30

[Command]
name = "multikick"
command = F,D,F,b
time = 30

[Command]
name = "multikick"
command = F,D,F,c
time = 30

;back kick
[Command]
name = "superkick"
command = D,B,a
time = 30

[Command]
name = "superkick"
command = D,B,b
time = 30

[Command]
name = "superkick"
command = D,B,c
time = 30

;===========================================================================
; Special Motions
;===========================================================================
;Huricane
[Command]
name = "hur"
command = D,F,D,F,x
time = 30

[Command]
name = "hur"
command = D,F,D,F,y
time = 30

[Command]
name = "hur"
command = D,F,D,F,z
time = 30

[Command]
name = "pamonha_kick"
command = ~D , DF , F , a
time = 20

[Command]
name = "pamonha_kick"
command = ~D , DF , F , b
time = 20

[Command]
name = "pamonha_kick"
command = ~D , DF , F , c
time = 20

[Command]
name = "U"
command = U

;===========================================================================
; Double Tap Motions
;===========================================================================
[Command]
name = "FF"     ;Required (do not remove)
command = F, F
time = 10

[Command]
name = "BB"     ;Required (do not remove)
command = B, B
time = 10

;===========================================================================
; 2/3 button combinations
;===========================================================================
[Command]
name = "recovery";Required (do not remove)
command = a+x
time = 1

;megablock
[Command]
name = "mega_block"
command = c+z
time = 50

;Cosmo Explosion
[Command]
name = "cosmo"
command = x+y+z
time = 40

;===========================================================================
; Directions + Buttons
;===========================================================================
[Command]
name = "down_a"
command = /$D,a
time = 1

[Command]
name = "down_b"
command = /$D,b
time = 1

;===========================================================================
; Singular Buttons
;===========================================================================
[Command]
name = "a"
command = a
time = 1

[Command]
name = "b"
command = b
time = 1

[Command]
name = "c"
command = c
time = 1

[Command]
name = "x"
command = x
time = 1

[Command]
name = "y"
command = y
time = 1

[Command]
name = "z"
command = z
time = 1

[Command]
name = "start"
command = s
time = 1

;===========================================================================
; Hold Direction
;===========================================================================
[Command]
name = "DU"
command = D, U
time = 10

[Command]
name = "UF"
command = UF
time = 1

[Command]
name = "UB"
command = UB
time = 1

[Command]
name = "DUF"
command = D, UF
time = 10

[Command]
name = "DUB"
command = D, UB
time = 10

[Command]
name = "up"
command = U
time = 1
[Command]
name = "holdfwd";Required (do not remove)
command = /$F
time = 1

[Command]
name = "holdback";Required (do not remove)
command = /$B
time = 1

[Command]
name = "holdup" ;Required (do not remove)
command = /$U
time = 1

[Command]
name = "holddown";Required (do not remove)
command = /$D
time = 1

;-----------------------
;superguard
[Command]
name = "holdback3"
command = /$B   
time = 50
;------------------------

;/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\|State Entry|/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
[Statedef -1]
;===========================================================================
; Hypers
;===========================================================================
;===========================================================================
[State -1]
type = ChangeState
value = 2000
triggerall = var(59) != 1
triggerall = statetype != A && (P2statetype != L)
triggerall = power >= 1000
triggerall = ctrl
trigger1 = command = "mt"

[State -1]
type = ChangeState
value = 2100
triggerall = var(59) != 1
triggerall = (statetype != A) && (P2statetype != L)
triggerall = power >= 500
triggerall = ctrl
trigger1 = command = "hur"

[State -1]
type = Varset
trigger1 = command = "vmt1"
v = 22
value = 1
[State -1]
type = Varset
trigger1 = command = "vmt2"
v = 22
value = 2
[State -1]
type = Varset
trigger1 = command = "vmt3"
v = 22
value = 3

[State -1]
type = ChangeState
value = 2200
triggerall = var(59) != 1
triggerall = statetype != A && (p2stateno <= 5000 || p2stateno > 6000)
triggerall = power >= 1000
triggerall = ctrl
trigger1 = command = "vmt1"
trigger2 = command = "vmt2"
trigger3 = command = "vmt3"

[State -1]
type = ChangeState
value = 2300
triggerall = var(59) != 1
triggerall = statetype != A
triggerall = power >= 1000
triggerall = ctrl
trigger1 = command = "mt2"
;===========================================================================
; Supers
;===========================================================================
;===========================================================================
[State -1]
type = Varset
trigger1 = command = "nudge1"
v = 12
value = 1
[State -1]
type = Varset
trigger1 = command = "nudge2"
v = 12
value = 2
[State -1]
type = Varset
trigger1 = command = "nudge3"
v = 12
value = 3

[state -1]
type = ChangeState
value = 1200
triggerall = var(59) != 1
triggerall = statetype != A
triggerall = ctrl
trigger1 = command = "nudge1"
trigger2 = command = "nudge2"
trigger3 = command = "nudge3"

[State -1]
type = ChangeState
value = 1300
triggerall = command = "throw"
triggerall = statetype = S
triggerall = ctrl
trigger1 = command = "holdback"
trigger1 = p2bodydist X < 10
trigger1 = p2statetype = S

[State -1]
type = ChangeState
value = 1700
triggerall = var(59) != 1
triggerall = command = "pamonha_kick"
trigger1 = statetype = A
trigger1 = ctrl = 1

[state -1]
type = ChangeState
value = 1500
triggerall = var(59) != 1
triggerall = statetype != A
triggerall = ctrl
trigger1 = command = "superkick"

[state -1]
type = ChangeState
value = 1600
triggerall = var(59) != 1
triggerall = ctrl
trigger1 = command = "multikick"

;===========================================================================
; Specials
;===========================================================================
;===========================================================================
     
;Cosmo Explosion
[State -1]
type = changestate
value = 990
triggerall = var(59) != 1
triggerall = command = "cosmo"
triggerall = power >= 3000
trigger1 = statetype != A
trigger1 = ctrl = 1

;---------------------------------------------------------------------------

;Mega block
[State -1]
type = ChangeState
value = 3685
triggerall = var(59) != 1
triggerall = command = "mega_block"
triggerall = command = "holdback"
trigger1 = statetype != A
trigger1 = ctrl = 1

;===========================================================================
; Basics
;===========================================================================
;---------------------------------------------------------------------------
; RunFwd
[State -1, Run Fwd]
type = ChangeState
value = 100
trigger1 = ((command = "FF") && (statetype = S) && (ctrl = 1))

;---------------------------------------------------------------------------
; Hop Back
[State -1, Run Back]
type = ChangeState
value = 105
trigger1 = ((command = "BB") && (statetype = S) && (ctrl = 1))

;------------------------------------------

;Stand A
[State -1, Standing Light Punch]
type = ChangeState
value = 200
triggerall = var(59) != 1
triggerall = command = "x"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl

;Stand B
[State -1, Standing Medium Punch]
type = ChangeState
value = 210
triggerall = var(59) != 1
triggerall = command = "y"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230
trigger2 = movecontact = 1

;Stand C
[State -1, Standing Strong Punch]
type = ChangeState
value = 220
triggerall = var(59) != 1
triggerall = command = "z"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 230
trigger2 = movecontact = 1
;----------------------------------

;Stand X
[State -1, Standing Light Kick]
type = ChangeState
value = 230
triggerall = var(59) != 1
triggerall = command = "a"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200
trigger2 = movecontact = 1

;Standing Y
[State -1, Standing Medium Kick]
type = ChangeState
value = 240
triggerall = var(59) != 1
triggerall = command = "b"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 210
trigger2 = movecontact = 1

;Standing Z
[State -1, Standing Strong Kick]
type = ChangeState
value = 250
triggerall = var(59) != 1
triggerall = command = "c"
triggerall = command != "holddown"
trigger1 = P2bodydist X >= 25
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 210 || stateno = 240 || stateno = 220
trigger2 = movecontact = 1

;Standing Z
[State -1, Standing Strong Kick]
type = ChangeState
value = 251
triggerall = var(59) != 1
triggerall = command = "c"
triggerall = command != "holddown"
trigger1 = P2bodydist X <= 24
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 210 || stateno = 240 || stateno = 220
trigger2 = movecontact = 1
;---------------------------------------------------------------------------
;Taunt
[State -1, Taunt]
type = ChangeState
value = 189
triggerall = var(59) != 1
triggerall = command = "start"
trigger1 = statetype != A
trigger1 = ctrl

;---------------------------------------------------------------------------
;Crouching A
[State -1, Crouching Light Punch]
type = ChangeState
value = 400
triggerall = var(59) != 1
triggerall = command = "x"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl

;Crouching B
[State -1, Crouching Medium Punch]
type = ChangeState
value = 410
triggerall = var(59) != 1
triggerall = command = "y"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl

;Crouching C
[State -1, Crouching Strong Punch]
type = ChangeState
value = 420
triggerall = var(59) != 1
triggerall = command = "z"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;Crouching X
[State -1, Crouching Light Kick]
type = ChangeState
value = 430
triggerall = var(59) != 1
triggerall = command = "a"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 400
trigger2 = movecontact = 1

;Crouching Y
[State -1, Crouching Medium Kick]
type = ChangeState
value = 440
triggerall = var(59) != 1
triggerall = command = "b"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 400
trigger2 = movecontact = 1

;Crouching Z
[State -1, Crouching Strong Kick]
type = ChangeState
value = 450
triggerall = var(59) != 1
triggerall = command = "c"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl
trigger2 = stateno = 200 || stateno = 230 || stateno = 210 || stateno = 400 || stateno = 430 || stateno = 410
trigger2 = movecontact = 1

;---------------------------------------------------------------------------
;Jump A
[State -1, Jump Light Punch]
type = ChangeState
value = 600
triggerall = var(59) != 1
triggerall = command = "x"
trigger1 = statetype = A
trigger1 = ctrl = 1 
trigger2 = stateno = 640
trigger2 = movehit = 1

;Jump B
[State -1, Jump Medium Punch]
type = ChangeState
value = 610
triggerall = var(59) != 1
triggerall = command = "y"
trigger1 = statetype = A
trigger1 = ctrl = 1 
trigger2 = stateno = 600
trigger2 = movecontact = 1


;Jump C
[State -1, Jump Strong Punch]
type = ChangeState
value = 620
triggerall = var(59) != 1
triggerall = command = "z"
trigger1 = statetype = A
trigger1 = ctrl
trigger2 = stateno = 600 || stateno = 630  || stateno = 640 
trigger2 = movecontact

;---------------------------------------------------------------------------
;Jump X
[State -1, Jump Light Kick]
type = ChangeState
value = 630
triggerall = var(59) != 1
triggerall = command = "a"
trigger1 = statetype = A
trigger1 = ctrl
trigger2 = stateno = 600 
trigger2 = movecontact

;Jump Y
[State -1, Jump Medium Kick]
type = ChangeState
value = 640
triggerall = var(59) != 1
triggerall = command = "b"
trigger1 = statetype = A
trigger1 = ctrl
trigger2 = stateno = 600 
trigger2 = movecontact

;Jump Z
[State -1, Jump Strong Kick]
type = ChangeState
value = 650
triggerall = var(59) != 1
triggerall = command = "c"
trigger1 = statetype = A
trigger1 = ctrl
trigger2 = stateno = 610 || stateno = 630
trigger2 = movecontact

;===========================================================================
; AI 
;===========================================================================
;===========================================================================
;activation
[State -1]
type = Varset
trigger1 = command = "CPU1"
trigger2 = command = "CPU2"
trigger3 = command = "CPU3"
trigger4 = command = "CPU4"
trigger5 = command = "CPU5"
trigger6 = command = "CPU6"
trigger7 = command = "CPU7"
trigger8 = command = "CPU8"
trigger9 = command = "CPU9"
trigger10 = command = "CPU10"
trigger11 = command = "CPU11"
trigger12 = command = "CPU12"
trigger13 = command = "CPU13"
trigger14 = command = "CPU14"
trigger15 = command = "CPU15"
trigger16 = command = "CPU16"
trigger17 = command = "CPU17"
trigger18 = command = "CPU18"
trigger19 = command = "CPU19"
trigger20 = command = "CPU20"
trigger21 = command = "CPU21"
trigger22 = command = "CPU22"
trigger23 = command = "CPU23"
trigger24 = command = "CPU24"
trigger25 = command = "CPU25"
trigger26 = command = "CPU26"
trigger27 = command = "CPU27"
trigger28 = command = "CPU28"
trigger29 = command = "CPU29"
trigger30 = command = "CPU30"
trigger31 = command = "CPU31"
trigger32 = command = "CPU32"
trigger33 = command = "CPU33"
trigger34 = command = "CPU34"
trigger35 = command = "CPU35"
trigger36 = command = "CPU36"
trigger37 = command = "CPU37"
trigger38 = command = "CPU38"
trigger39 = command = "CPU39"
trigger40 = command = "CPU40"
trigger41 = command = "CPU41"
trigger42 = command = "CPU42"
trigger43 = command = "CPU43"
trigger44 = command = "CPU44"
trigger45 = command = "CPU45"
trigger46 = command = "CPU46"
trigger47 = command = "CPU47"
trigger48 = command = "CPU48"
v = 59
value = 1

;===========================================================================
; Hypers
;===========================================================================
;===========================================================================
[State -1]
type = ChangeState
value = 2000
triggerall = var(59) = 1
triggerall = statetype != A && (P2statetype != L)
trigger1 = power >= 1800
trigger1 = random <= 100
trigger1 = ctrl


[State -1]
type = ChangeState
value = 2100
triggerall = var(59) = 1
triggerall = statetype = S
trigger1 = power >= 500
trigger1 = (P2Dist x >= 80)&&(P2Dist x <= 200)
trigger1 = random <= 50
trigger1 = ctrl


[State -1]
type = Varset
trigger1 = var(59) = 1
trigger1 = (P2Dist x >= 60)&&(P2Dist x <= 160)
v = 22
value = 1
[State -1]
type = Varset
trigger1 = var(59) = 1
trigger1 = (P2Dist x > 160)&&(P2Dist x <= 240)
v = 22
value = 2
[State -1]
type = Varset
trigger1 = var(59) = 1
trigger1 = (P2Dist x > 240)
v = 22
value = 3

[State -1]
type = ChangeState
value = 2200
triggerall = var(59) = 1
triggerall = statetype != A && (p2stateno <= 5000 || p2stateno > 6000)
trigger1 = ((var(22) = 1)&&(P2Dist x >= 60)&&(P2Dist x <= 160))||((var(22) = 2)&&(P2Dist x > 160)&&(P2Dist x <= 240))||((var(22) = 3)&&(P2Dist x > 240))
trigger1 = power >= 1300
trigger1 = random <= 100
trigger1 = ctrl


[State -1]
type = ChangeState
value = 2300
triggerall = var(59) = 1
triggerall = statetype != A && P2statetype = S
trigger1 = power >= 1300
trigger1 = P2Dist x <= 120
trigger1 = random <= 100
trigger1 = ctrl
;===========================================================================
; Supers
;===========================================================================
;===========================================================================
[State -1]
type = Varset
trigger1 = var(59) = 1
trigger1 = P2Dist x <= 100
v = 12
value = 1
[State -1]
type = Varset
trigger1 = var(59) = 1
trigger1 = (P2Dist x > 100)&&(P2Dist x <= 200)
v = 12
value = 2
[State -1]
type = Varset
trigger1 = var(59) = 1
trigger1 = P2Dist x > 200
v = 12
value = 3

[state -1]
type = ChangeState
value = 1200
triggerall = var(59) = 1
triggerall = statetype = S
trigger1 = ((var(12) = 1)&&(P2Dist x <= 100))||((var(12) = 2)&&(P2Dist x > 100)&&(P2Dist x <= 200))||((var(12) = 3)&&(P2Dist x > 200))
trigger1 = random <= 100
trigger1 = ctrl

[State -1]
type = ChangeState
value = 1300
triggerall = var(59) = 1
triggerall = statetype = S 
trigger1 = p2bodydist X < 20
trigger1 = p2statetype = S
trigger1 = random <= 100
trigger1 = ctrl

[State -1]
type = ChangeState
value = 1700
triggerall = var(59) = 1
triggerall = statetype = A && (P2statetype = S || P2statetype = C || P2statetype = A)
triggerall = ctrl
trigger1 = P2Dist x >= 175 && P2Dist y >= P2Dist x - 80
trigger1 = Vel X != 0
trigger1 = random <= 600
trigger2 = P2Dist x <= 50 && P2Dist y >= 100
trigger2 = FrontEdgeDist <= 50
trigger2 = random <= 500

[state -1]
type = ChangeState
value = 1500
triggerall = var(59) = 1
triggerall = statetype = S
trigger1 = random <= 50
trigger1 = P2Dist x >= 150
trigger1 = ctrl

[state -1]
type = ChangeState
value = 1600
triggerall = var(59) = 1
triggerall = statetype = S
trigger1 = P2Dist x <= 100
trigger1 = random <= 100
trigger1 = ctrl

;===========================================================================
; Specials
;===========================================================================
;===========================================================================
     
[State -1]
type = changestate
value = 990
triggerall = var(59) = 1
triggerall = var(9) != 1
triggerall = power >= 2990
trigger1 = statetype != A
trigger1 = random <= 950
trigger1 = ctrl

[State -1]
type = ChangeState
value = 3685
triggerall = var(59) = 1
trigger1 = P2Dist x <= 70 && P2Dist y <= 0 && P2Dist y >= -50
trigger1 = statetype != A && P2movetype = A
trigger1 = random <= 600
trigger1 = ctrl = 1

;===========================================================================
; Basics
;===========================================================================
[State -1]
type = ChangeState
value = 40
triggerall = var(59) = 1
triggerall = statetype = S
triggerall = P2Life >= 50
trigger1 = P2Dist x > 120
trigger1 = random <= 300
trigger1 = ctrl

[State -1]
type = ChangeState
value = 105
triggerall = var(59) = 1
triggerall = statetype = S
trigger1 = P2Dist x <= 100
trigger1 = random <= 700
trigger1 = ctrl

[State -1]
type = ChangeState
value = 189
triggerall = var(59) = 1
trigger1 = statetype = S && P2statetype = L
trigger1 = life >= P2life + 500
trigger1 = random <= 100
trigger1 = ctrl
trigger2 = statetype = S
trigger2 = P2Dist x >= 220
trigger2 = life >= P2life + 100
trigger2 = random <= 40
trigger2 = ctrl

[State -1]
type = ChangeState
value = 200
triggerall = var(59) = 1
triggerall = statetype = S
trigger1 = P2Dist x <= 120
trigger1 = random <= 800
trigger1 = ctrl

[State -1]
type = ChangeState
value = 210
triggerall = var(59) = 1
trigger1 = stateno = 200
trigger1 = movecontact = 10
trigger1 = random <= 800
trigger2 = statetype = S
trigger2 = P2Dist x <= 100
trigger2 = random <= 600
trigger2 = ctrl

[State -1]
type = ChangeState
value = 220
triggerall = var(59) = 1
trigger1 = statetype = S && (P2statetype = S || P2statetype = A)
trigger1 = P2Dist x >= 70 && P2Dist x <= 130
trigger1 = random <= 200
trigger1 = ctrl
trigger2 = statetype = S
trigger2 = P2Dist x >= 170
trigger2 = random <= 600
trigger2 = ctrl

[State -1]
type = ChangeState
value = 230
triggerall = var(59) = 1
triggerall = statetype = S
trigger1 = P2Dist x <= 100
trigger1 = random <= 600
trigger1 = ctrl

[State -1]
type = ChangeState
value = 240
triggerall = var(59) = 1
trigger1 = stateno = 230
trigger1 = movecontact = 10
trigger1 = random <= 500
trigger2 = P2Dist x <= 100
trigger2 = statetype = S
trigger2 = random <= 700
trigger2 = ctrl

[State -1]
type = ChangeState
value = 250
triggerall = var(59) = 1
trigger1 = stateno = 251
trigger1 = movecontact = 5
trigger1 = random <= 600
trigger2 = P2Dist x >= 80 && P2Dist x <= 160
trigger2 = statetype = S
trigger2 = random <= 600
trigger2 = ctrl
trigger3 = statetype = S
trigger3 = P2Dist x >= 200
trigger3 = random <= 300
trigger3 = ctrl

[State -1]
type = ChangeState
value = 251
triggerall = var(59) = 1
trigger1 = stateno = 250 
trigger1 = movecontact = 10
trigger1 = random <= 700
trigger2 = P2Dist x <= 40
trigger2 = statetype = S
trigger2 = random <= 700
trigger2 = ctrl

[State -1]
type = ChangeState
value = 400
triggerall = var(59) = 1
trigger1 = stateno = 600 
trigger1 = movecontact = 10
trigger1 = random <= 500
trigger2 = statetype = C && P2statetype = C
trigger2 = P2Dist x <= 40
trigger2 = random <= 300
trigger2 = ctrl

[State -1]
type = ChangeState
value = 410
triggerall = var(59) = 1
trigger1 = stateno = 600 
trigger1 = movecontact = 10
trigger1 = random <= 400
trigger2 = statetype = C && (P2statetype = S || P2statetype = C)
trigger2 = P2Dist x <= 60
trigger2 = random <= 600
trigger2 = ctrl

[State -1]
type = ChangeState
value = 420
triggerall = var(59) = 1
trigger1 = stateno = 210 
trigger1 = movecontact = 10
trigger1 = random <= 600
trigger2 = stateno = 410 
trigger2 = movecontact = 10
trigger2 = random <= 700
trigger3 = stateno = 220 
trigger3 = movecontact = 10
trigger3 = random <= 400
trigger4 = statetype = C && (P2statetype = S || P2statetype = C)
trigger4 = P2Dist x >= 50 && P2Dist x <= 80
trigger4 = random <= 800
trigger4 = ctrl

[State -1]
type = ChangeState
value = 430
triggerall = var(59) = 1
trigger1 = stateno = 630 
trigger1 = movecontact = 10
trigger1 = random <= 600
trigger2 = stateno = 230 
trigger2 = movecontact = 10
trigger2 = random <= 200
trigger3 = statetype = C && P2statetype = C
trigger3 = P2Dist x <= 40
trigger3 = random <= 400
trigger3 = ctrl

[State -1]
type = ChangeState
value = 440
triggerall = var(59) = 1
trigger1 = statetype = C && (P2statetype = S || P2statetype = C)
trigger1 = P2Dist x <= 60
trigger1 = random <= 600
trigger1 = ctrl
trigger2 = stateno = 420
trigger2 = movecontact = 10
trigger2 = random <= 300

[State -1]
type = ChangeState
value = 450
triggerall = var(59) = 1
trigger1 = statetype = C && (P2statetype = S || P2statetype = C)
trigger1 = P2Dist x >= 60 && P2Dist x <= 90
trigger1 = random <= 500
trigger1 = ctrl
trigger2 = stateno = 440
trigger2 = movecontact = 10
trigger2 = random <= 300

[State -1]
type = ChangeState
value = 600
triggerall = var(59) = 1
triggerall = statetype = A && P2statetype = S
trigger1 = P2Dist x <= 30 && P2Dist y <= 10 && P2Dist y >= -10
trigger1 = random <= 400
trigger1 = ctrl

[State -1]
type = ChangeState
value = 610
triggerall = var(59) = 1
triggerall = statetype = A && P2statetype = A
trigger1 = P2Dist x <= 50 && P2Dist y <= 5 && P2Dist y >= -5
trigger1 = random <= 400
trigger1 = ctrl

[State -1]
type = ChangeState
value = 620
triggerall = var(59) = 1
triggerall = statetype = A
trigger1 = P2Dist x <= 70
trigger1 = vel x > 0
trigger1 = random <= 500
trigger1 = ctrl

[State -1]
type = ChangeState
value = 630
triggerall = var(59) = 1
triggerall = statetype = A && P2statetype = S
trigger1 = P2Dist x <= 30 && P2Dist y <= 10 && P2Dist y >= -10
trigger1 = random <= 700
trigger1 = ctrl

[State -1]
type = ChangeState
value = 640
triggerall = var(59) = 1
triggerall = statetype = A
trigger1 = P2Dist x <= 100
trigger1 = vel x > 0
trigger1 = random <= 700
trigger1 = ctrl

[State -1]
type = ChangeState
value = 650
triggerall = var(59) = 1
triggerall = statetype = A && P2statetype = A
trigger1 = P2Dist x <= 50 && P2Dist y <= 5 && P2Dist y >= -5
trigger1 = random <= 800
trigger1 = ctrl
